DjangoAssessment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("heroes/", include("assessment.urls"))
]

assessment/urls.py
from django.urls import path
from .views import MyLoginView,SuperHeroListView, SuperHeroDetailView, SuperHeroCreateView, SuperHeroUpdateView

app_name = "legal"
urlpatterns = [
    path("", MyLoginView.as_view(), name='login'),
    path("superhero/", SuperHeroListView.as_view(), name="list"),
    path("superhero/<int:pk>/detail/", SuperHeroDetailView.as_view(), name="detail"),
    path("create/", SuperHeroCreateView.as_view(), name="add_superhero"),
    path("update/<int:pk>/", SuperHeroUpdateView.as_view(), name="update_superhero"),
]

assessment/models.py
from django.db import models


class SuperHero(models.Model):
    name = models.CharField(max_length=50, blank=False, null=False)
    alignment = models.CharField(max_length=10, blank=False, null=False)
    height = models.IntegerField(null=True, blank=True)
    weight = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.name

assessment/forms.py
from django import forms
from .models import SuperHero


class SuperHeroForm(forms.ModelForm):
    class Meta:
        model = SuperHero
        fields = ['name', 'alignment', 'height', 'weight']

assessment/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import SuperHero

# custom imports
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView
from .forms import SuperHeroForm


class MyLoginView(LoginView):
    template_name = 'registration/login.html'
    success_url = reverse_lazy('legal:list')


class SuperHeroCreateView(CreateView):
    model = SuperHero
    form_class = SuperHeroForm
    template_name = 'assessment/superhero_form.html'
    success_url = reverse_lazy('legal:list')


class SuperHeroUpdateView(UpdateView):
    model = SuperHero
    form_class = SuperHeroForm
    template_name = 'assessment/superhero_form.html'
    success_url = reverse_lazy('legal:list')


class SuperHeroListView(LoginRequiredMixin, ListView):
    model = SuperHero
    login_url = reverse_lazy('legal:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class SuperHeroDetailView(LoginRequiredMixin, DetailView):
    model = SuperHero
    login_url = reverse_lazy('legal:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(context)
        return context

templates/assessment/superhero_detail.html
{% extends 'base.html' %}

{% block navbar_items %}
    {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'legal:list' %}">List</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'legal:add_superhero' %}">Create</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'legal:login' %}">Logout</a>
        </li>
    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'legal:login' %}">Register</a>
        </li>
    {% endif %}
{% endblock %}

{% block content %}
    <table class="table">
        <thead>
            <tr><th scope="col">Name</th><th scope="col">Alignment</th><th scope="col">Height</th><th scope="col">Weight</th></tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ object.name }}</td>
                <td>{{ object.alignment }}</td>
                <td>{{ object.height }}</td>
                <td>{{ object.weight }}</td>
            </tr>
        </tbody>
    </table>

{% endblock %}

templates/assessment/superhero_form.html
{% extends 'base.html' %}

{% block navbar_items %}
    {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'legal:list' %}">List</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'legal:add_superhero' %}">Create</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'legal:login' %}">Logout</a>
        </li>
    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'legal:login' %}">Register</a>
        </li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>Add a Superhero</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
{% endblock %}

templates/assessment/superhero_list.html
{% extends 'base.html' %}

{% block navbar_items %}
    {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'legal:list' %}">List</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'legal:add_superhero' %}">Create</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'legal:login' %}">Logout</a>
        </li>
    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'legal:login' %}">Register</a>
        </li>
    {% endif %}
{% endblock %}

{% block content %}
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Super Hero Name</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
                <tr>
                    <td>{{ object.name }}</td>
                    <td>
                        <a href="{{ object.pk }}/detail/" class="btn btn-primary">
                            <i class="far fa-eye"></i> View
                        </a>
                        <a href="{% url 'legal:update_superhero' object.pk %}" class="btn btn-primary">
                            <i class="fas fa-pencil-alt"></i> Edit
                        </a>
                    </td>
                </tr>
            {% empty %}
                <tr><td colspan="4">No Superheroes yet. Create one!</td>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Super Heroes</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" href="#">Super Heroes</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    {% block navbar_items %}{% endblock %}
                </ul>
            </div>
        </nav>

        <div class="row">
            <div class="col">
                {% block content %}

                {% endblock %}
            </div>
        </div>
    </div>

</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</html>